apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: python-deploy
  name: python-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-deploy
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: python-deploy
    spec:
      containers:
      - image: %IMG_NAME%
        name: python-docker-flask
