apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: python-deploy
  name: python-deploy
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: python-deploy
  type: NodePort
status:
  loadBalancer: {}
